export let levels = [
  {
    level: 100,
    semesters: {
      firstSemester: {
        courses: [
          {
            courseTitle: "Communication Skills in English",
            courseCode: "GES 100",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "General Biology",
            courseCode: "FSB 101",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Introduction to Mechanics and Properties of Matter",
            courseCode: "PHY 101",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Laboratory Practice I",
            courseCode: "PHY 102",
            creditUnit: 1,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Algebra and Trigonometry",
            courseCode: "MTH 110",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Calculus",
            courseCode: "MTH 120",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "General Chemistry I",
            courseCode: "CHM 130",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
        ],
        creditLoad: 24,
      },
      secondSemester: {
        courses: [
          {
            courseTitle: "Introduction to Logic and Philosophy",
            courseCode: "GES 102",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Computer Appreciation and Application",
            courseCode: "GES 101",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "General Biology II",
            courseCode: "FSB 102",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Heat, Light and Sound",
            courseCode: "PHY 115",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Nigeria: Peoples and Culture",
            courseCode: "GES 103",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Introduction to Principles of Organic Chemistry",
            courseCode: "CHM 132",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
        ],
        creditLoad: 24,
      },
    },
    gpa: 0.00,
  },
  {
    level: 200,
    semesters: {
      firstSemester: {
        courses: [
          {
            courseTitle: "Animal Behaviour",
            courseCode: "AEB 205",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "General Biochemistry",
            courseCode: "BCH 210",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Organic Chemistry",
            courseCode: "CHM 260",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Introduction to Computer Programming",
            courseCode: "CSC 280",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Cell Biology",
            courseCode: "FSB 201",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "General Microbiology I",
            courseCode: "MCB 200",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Structure and Function of Seed Plants",
            courseCode: "PSB 201",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
        ],
        creditLoad: 24,
      },
      secondSemester: {
        courses: [
          {
            courseTitle: "Lower Invertebrates",
            courseCode: "AEB 200",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Higher Invertebrates",
            courseCode: "AEB 201",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Genetics I",
            courseCode: "FSB 202",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Biological Techniques II",
            courseCode: "FSB 203",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "General Ecology",
            courseCode: "FSB 204",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Community Service",
            courseCode: "FSC 2CI",
            creditUnit: 1,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Seedless Plants II",
            courseCode: "PSB 206",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Statistics for Biological and Agricultural Science",
            courseCode: "STA 264",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
        ],
        creditLoad: 24,
      },
    },
    gpa: 0.00,
  },
  {
    level: 300,
    semesters: {
      firstSemester: {
        courses: [
          {
            courseTitle: "Fundamentals of Entrepreneurship",
            courseCode: "GES 300",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Hydrobiology & Ichthyology",
            courseCode: "AEB 300",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Introductory Parasitology",
            courseCode: "AEB 301",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Protochordates and Chordates",
            courseCode: "AEB 302",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Environmental Assessment and Conservation Science",
            courseCode: "AEB 381",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Terrestrial Arthropods",
            courseCode: "AEB 382",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Animal Physiology",
            courseCode: "AEB 383",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Genetics II",
            courseCode: "FSB 301",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Molecular Biology I",
            courseCode: "FSB 302",
            creditUnit: 2,
            grade: "",
            qp: 0,
          },
          {
            courseTitle: "Population and Production Ecology",
            courseCode: "FSB 303",
            creditUnit: 3,
            grade: "",
            qp: 0,
          },
        ],
        creditLoad: 24,
      },
      secondSemester: {
        courses: [
          {
            courseTitle: "Students Industrial Work Experience Scheme" || "SIWES",
            courseCode: "AEB 380",
            creditUnit: 9,
            grade: "",
            qp: 0,
          },
        ],
        creditLoad: 24,
      },
    },
    gpa: 0.00,
  },
  {
    level: 400,
    courseOptions: [
      {
        name: "Animal Physiology",
        semesters: {
          firstSemester: {
            courses: [
              {
                courseTitle: "Essentials of Entrepreneurship",
                courseCode: "GES 400",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Comparative Vertebrate Anatomy and Physiology",
                courseCode: "AEB 451",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Histology and Pathology",
                courseCode: "AEB 454",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Molecular Biology and Genetic Engineering",
                courseCode: "AEB 458",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Research Methodology",
                courseCode: "AEB 480",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Health and Safety",
                courseCode: "AEB 484",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Basic Endocrinology",
                courseCode: "AEB 455",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Animal Production and Management",
                courseCode: "AEB 452",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Pest Diseases and Animal Health",
                courseCode: "AEB 453",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Nigerian Feeds, Feedstuff and Animal Care",
                courseCode: "AEB 470",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
            ],
            creditLoad: 24,
          },
          secondSemester: {
            courses: [
              {
                courseTitle: "Seminar",
                courseCode: "AEB 481",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Project",
                courseCode: "AEB 482",
                creditUnit: 6,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Policies and Laws",
                courseCode: "AEB 487",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Waste Management",
                courseCode: "AEB 488",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Special Topics in Animal Physiology",
                courseCode: "AEB 456",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Developmental and Reproductive Physiology",
                courseCode: "AEB 457",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Immunology and Immunopathology",
                courseCode: "AEB 441",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Pharmacological Animal Physiology",
                courseCode: "AEB 459",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Animal Nutrition and Metabolism",
                courseCode: "AEB 460",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
            ],
            creditLoad: 24,
          },
        },
        gpa: 0.00,
      },
      {
        name: "Entomology",
        semesters: {
          firstSemester: {
            courses: [
              {
                courseTitle: "Essentials of Entrepreneurship",
                courseCode: "GES 400",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Comparative Vertebrate Anatomy and Physiology",
                courseCode: "AEB 451",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Histology and Pathology",
                courseCode: "AEB 454",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Molecular Biology and Genetic Engineering",
                courseCode: "AEB 458",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Research Methodology",
                courseCode: "AEB 480",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Health and Safety",
                courseCode: "AEB 484",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Plant Pathology",
                courseCode: "PSB 401",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Medical and Veterinary Entomology",
                courseCode: "AEB 410",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Pests of Field Crops and Stored Products",
                courseCode: "AEB 411",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Biodiversity, Forest and Wildlife Management",
                courseCode: "AEB 486",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Arachnology",
                courseCode: "AEB 412",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
            ],
            creditLoad: 24,
          },
          secondSemester: {
            courses: [
              {
                courseTitle: "Seminar",
                courseCode: "AEB 481",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Project",
                courseCode: "AEB 482",
                creditUnit: 6,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Policies and Laws",
                courseCode: "AEB 487",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Waste Management",
                courseCode: "AEB 488",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Insect Pest Management",
                courseCode: "AEB 420",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Aquatic Entomology",
                courseCode: "AEB 422",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Applied Parasitology and Parasite Biochemistry",
                courseCode: "AEB 440",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: false,
              },
            ],
            creditLoad: 24,
          },
        },
        gpa: 0.00,
      },
      {
        name: "Parasitology",
        semesters: {
          firstSemester: {
            courses: [
              {
                courseTitle: "Essentials of Entrepreneurship",
                courseCode: "GES 400",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Comparative Vertebrate Anatomy and Physiology",
                courseCode: "AEB 451",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Histology and Pathology",
                courseCode: "AEB 454",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Molecular Biology and Genetic Engineering",
                courseCode: "AEB 458",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Research Methodology",
                courseCode: "AEB 480",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Health and Safety",
                courseCode: "AEB 484",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Ecology, Taxonomy and Diagnoses of Parasites",
                courseCode: "AEB 430",
                creditUnit: 2,
                grade: "",
                qp: 0,
              },
              {
                courseTitle: "Epidemiology and Pathology",
                courseCode: "AEB 432",
                creditUnit: 2,
                grade: "",
                qp: 0,
              },
              {
                courseTitle: "Agro-Nematology",
                courseCode: "AEB 433",
                creditUnit: 2,
                grade: "",
                qp: 0,
              },
              {
                courseTitle: "Techniques in Environmental Studies",
                courseCode: "AEB 483",
                creditUnit: 2,
                grade: "",
                qp: 0,
              },
              {
                courseTitle: "Fish Diseases and Parasites",
                courseCode: "AEB 471",
                creditUnit: 2,
                grade: "",
                qp: 0,
              },
              {
                courseTitle: "Arachnology",
                courseCode: "AEB 412",
                creditUnit: 3,
                grade: "",
                qp: 0,
              },
            ],
            creditLoad: 24,
          },
          secondSemester: {
            courses: [
              {
                courseTitle: "Seminar",
                courseCode: "AEB 481",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Project",
                courseCode: "AEB 482",
                creditUnit: 6,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Policies and Laws",
                courseCode: "AEB 487",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Waste Management",
                courseCode: "AEB 488",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Immunology and Immuno-pathology",
                courseCode: "AEB 441",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Applied Parasitology and Parasite Biochemistry",
                courseCode: "AEB 440",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Insect Pest Management",
                courseCode: "AEB 420",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
            ],
            creditLoad: 24,
          },
        },
        gpa: 0.00,
      },
      {
        name: "Hydrobiology",
        semesters: {
          firstSemester: {
            courses: [
              {
                courseTitle: "Essentials of Entrepreneurship",
                courseCode: "GES 400",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Comparative Vertebrate Anatomy and Physiology",
                courseCode: "AEB 451",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Histology and Pathology",
                courseCode: "AEB 454",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Molecular Biology and Genetic Engineering",
                courseCode: "AEB 458",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Research Methodology",
                courseCode: "AEB 480",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Health and Safety",
                courseCode: "AEB 484",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Nigerian Feeds, Feedstuff and Animal Care",
                courseCode: "AEB 470",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Fish Diseases and Parasites",
                courseCode: "AEB 471",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Productivity of Natural and Man-maded Water Bodies",
                courseCode: "AEB 474",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Oceanography",
                courseCode: "AEB 475",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
              {
                courseTitle: "Evolution and Zoogeography",
                courseCode: "AEB 406",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
            ],
            creditLoad: 24,
          },
          secondSemester: {
            courses: [
              {
                courseTitle: "Seminar",
                courseCode: "AEB 481",
                creditUnit: 3,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Project",
                courseCode: "AEB 482",
                creditUnit: 6,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Environmental Policies and Laws",
                courseCode: "AEB 487",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Waste Management",
                courseCode: "AEB 488",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: true,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Aquaculture, Ornamental Fisheries and Fish Processing",
                courseCode: "AEB 476",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Fish Population Dynamics and Fisheries Policies and Modeling",
                courseCode: "AEB 477",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: true,
                isElective: false,
              },
              {
                courseTitle: "Climatology and Biogeography",
                courseCode: "AEB 479",
                creditUnit: 2,
                grade: "",
                qp: 0,
                isGeneral: false,
                isMandatory: false,
                isElective: true,
              },
            ],
            creditLoad: 24,
          },
        },
        gpa: 0.00,
      },
    ],
    activeOptionIndex: 0,
  },
];
